kind: Deployment
apiVersion: apps/v1
metadata:
  name: fsip-web
  namespace: fsip
  labels:
    k8s-app: fsip-web
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: fsip-web
  template:
    metadata:
      name: fsip-web
      labels:
        k8s-app: fsip-web
    spec:
      containers:
        - name: fsip-web
          image: 'harbor.dcos.xixian.unicom.local/img-freerdhn/fsip-web'
          imagePullPolicy: Always
          resources:
            requests:
              memory: 1Gi
            limits:
              memory: 2Gi
          livenessProbe:
            httpGet:
              path: /
              port: 9000
              scheme: HTTP
            initialDelaySeconds: 90
            timeoutSeconds: 2
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 3
