FROM harbor.dcos.xixian.unicom.local/img-freerdhn/busi-nginx:17.1_1
COPY dist/ /usr/share/nginx/html/dist/

COPY nginx.conf /usr/nginx/conf/nginx.conf
RUN /bin/cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && echo 'Asia/Shanghai' >/etc/timezone
